"""Add fabric, size, length to clothing items

Revision ID: 83660d34d834
Revises: c738da4ddd8e
Create Date: 2025-03-25 02:40:44.024162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83660d34d834'
down_revision: Union[str, None] = 'c738da4ddd8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('fabric', sa.String(), nullable=True))
    op.add_column('clothes', sa.Column('size', sa.String(), nullable=True))
    op.add_column('clothes', sa.Column('length', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'length')
    op.drop_column('clothes', 'size')
    op.drop_column('clothes', 'fabric')
    # ### end Alembic commands ###
